export enum Models {
  // OpenAI models
  ChatGPT_4K = 'ChatGPT (4K context)',
  ChatGPT_16K = 'ChatGPT (16K context)',
  GPT_35_Turbo_16K_0125 = 'ChatGPT (16K context, 0125)',
  GPT_35_Turbo_Instruct = 'gpt-3.5-turbo-instruct',
  GPT_4 = 'gpt-4 (8K context)',
  GPT_4_Turbo = 'GPT-4 Turbo',
  GPT_4o = 'GPT-4o',
  GPT_4o_Mini = 'GPT-4o mini',
  GPT_4_Turbo_0125 = 'GPT-4 Turbo (0125)',
  GPT_4_128K = 'gpt-4 (128K context)',
  Babbage_2 = 'babbage-002',
  Davinci_2 = 'davinci-002',
  O1_Preview = 'o1-preview',
  O1_Mini = 'o1-mini',

  // Azure models
  Azure_ChatGPT_4K = 'ChatGPT (4K context) (Azure)',
  Azure_ChatGPT_16K = 'ChatGPT (16K context) (Azure)',
  Azure_GPT_35_Turbo_Instruct = 'gpt-3.5-turbo-instruct (Azure)',
  Azure_GPT_4 = 'gpt-4 (Azure)',
  Azure_GPT_4o = 'GPT-4o (Azure)',
  Azure_GPT_4o_Mini = 'GPT-4o mini (Azure)',

  // Vertex AI models
  Text_Bison = 'text-bison',
  Text_Bison_001 = 'text-bison@001',
  Gemini_Pro = 'gemini-1.0-pro',
  Gemini_15_Flash = 'gemini-1.5-flash',
  Gemini_15_Pro = 'gemini-1.5-pro',

  // AWS Bedrock models
  AWS_Titan_TG1_Large = 'AWS - Titan TG1 Large (Bedrock)',
  AWS_Titan_Text_Lite_V1 = 'AWS - Titan Lite v1 (Bedrock)',
  AWS_Titan_Text_Express_V1 = 'AWS - Titan Express v1 (Bedrock)',
  Cohere_Command_R_V1 = 'Cohere - Command R v1 (Bedrock)',
  Cohere_Command_R_Plus_V1 = 'Cohere - Command R+ v1 (Bedrock)',
  Cohere_Command_Text_V14 = 'Cohere - Command v14 (Bedrock)',
  Cohere_Command_Light_Text_V14 = 'Cohere - Command Light v14 (Bedrock)',
  AI21_J2_Mid_V1 = 'AI21 - Jurassic-2 Mid v1 (Bedrock)',
  AI21_J2_Ultra_V1 = 'AI21 - Jurassic-2 Ultra v1 (Bedrock)',
  Anthropic_Claude_Instant_V1 = 'Anthropic - Claude Instant v1 (Bedrock)',
  Anthropic_Claude_V1 = 'Anthropic - Claude v1 (Bedrock)',
  Anthropic_Claude_V2 = 'Anthropic - Claude v2 (Bedrock)',
  Anthropic_Claude_V21 = 'Anthropic - Claude v2.1 (Bedrock)',
  Anthropic_Claude_3_Sonnet = 'Anthropic - Claude 3 Sonnet (Bedrock)',
  Anthropic_Claude_3_Haiku = 'Anthropic - Claude 3 Haiku (Bedrock)',
  Anthropic_Claude_3_Opus = 'Anthropic - Claude 3 Opus (Bedrock)',
  Anthropic_Claude_35_Sonnet = 'Anthropic - Claude 3.5 Sonnet (Bedrock)',
  Meta_Llama2_13B_Chat_V1 = 'Meta - Llama 2 Chat 13B v1 (Bedrock)',
  Meta_Llama3_8B_Instruct_V1 = 'Meta - Llama 3 8B Instruct v1 (Bedrock)',
  Meta_Llama3_70B_Instruct_V1 = 'Meta - Llama 3 70B Instruct v1 (Bedrock)',
  Mistral_7B_Instruct = 'Mistral - 7B Instruct (Bedrock)',
  Mistral_8x7B_Instruct = 'Mixtral - 8x7B Instruct (Bedrock)',
  Mistral_Large = 'Mistral - Large (Bedrock)',

  // Writer models
  Palmyra_Base = 'Palmyra Base',
  Palmyra_Large = 'Palmyra Large',
  Palmyra_Instruct = 'Palmyra Instruct',
  Palmyra_Instruct_30 = 'Palmyra Instruct 30',
  Palmyra_Beta = 'Palmyra Beta',
  Silk_Road = 'Silk Road',
  Palmyra_E = 'Palmyra E',
  Palmyra_X = 'Palmyra X',
  Palmyra_X_32K = 'Palmyra X 32K',
  Palmyra_Med = 'Palmyra Med',
  ExamWorks_V1 = 'Exam Works'
}
