from enum import Enum


class ScorerName(str, Enum):
    VALUE_0 = "_completeness_gpt"
    VALUE_1 = "_context_relevance"
    VALUE_10 = "_sexist"
    VALUE_11 = "_input_sexist"
    VALUE_12 = "_tone"
    VALUE_13 = "_input_tone"
    VALUE_14 = "_toxicity"
    VALUE_15 = "_input_toxicity"
    VALUE_16 = "_user_registered"
    VALUE_17 = "_user_submitted"
    VALUE_18 = "_user_generated"
    VALUE_19 = "_uncertainty"
    VALUE_2 = "_chunk_attribution_utilization_gpt"
    VALUE_20 = "_bleu"
    VALUE_21 = "_cost"
    VALUE_22 = "_rouge"
    VALUE_23 = "_prompt_injection"
    VALUE_24 = "_rag_nli"
    VALUE_25 = "_adherence_nli"
    VALUE_26 = "_completeness_nli"
    VALUE_27 = "_chunk_attribution_utilization_nli"
    VALUE_28 = "_instruction_adherence"
    VALUE_29 = "_ground_truth_adherence"
    VALUE_3 = "_factuality"
    VALUE_30 = "_tool_selection_quality"
    VALUE_31 = "_tool_error_rate"
    VALUE_32 = "_agentic_workflow_success"
    VALUE_33 = "_customized_completeness_gpt"
    VALUE_34 = "_customized_factuality"
    VALUE_35 = "_customized_groundedness"
    VALUE_36 = "_customized_chunk_attribution_utilization_gpt"
    VALUE_37 = "_customized_instruction_adherence"
    VALUE_38 = "_customized_ground_truth_adherence"
    VALUE_39 = "_customized_tool_selection_quality"
    VALUE_4 = "_groundedness"
    VALUE_40 = "_customized_tool_error_rate"
    VALUE_41 = "_customized_agentic_workflow_success"
    VALUE_5 = "_latency"
    VALUE_6 = "_prompt_perplexity"
    VALUE_7 = "_protect_status"
    VALUE_8 = "_pii"
    VALUE_9 = "_input_pii"

    def __str__(self) -> str:
        return str(self.value)
